"""debugging baseinfomodel by adding db into before and after lifecycles

Revision ID: 4074855bfd03
Revises: eb4376dfd49a
Create Date: 2024-05-18 23:29:47.333816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4074855bfd03'
down_revision: Union[str, None] = 'eb4376dfd49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
